platform :ios, '13.0'
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'

# 禁止所有 Pods 库的警告
inhibit_all_warnings!

# 在你的项目主 Target 中定义依赖
target 'RxSwift02' do
  # use_frameworks! # 使用动态框架（Swift 库需要）

  pod 'PromiseKit'
  pod 'Alamofire'
  pod 'SnapKit'
 pod 'RxSwift', '~> 6.5'       # 核心库
pod 'RxCocoa', '~> 6.5'       # UI 扩展
pod 'RxRelay', '~> 6.5'       # Relay 类型
pod 'RxDataSources', '~> 5.0' # 列表数据源
pod 'RxAlamofire', '~> 6.1'   # 网络请求

end
